export default {
  data: {
    "@context": [
      "https://geojson.org/geojson-ld/geojson-context.jsonld",
      {
        "@version": "1.1",
        wx: "https://api.weather.gov/ontology#",
        geo: "http://www.opengis.net/ont/geosparql#",
        unit: "http://codes.wmo.int/common/unit/",
        "@vocab": "https://api.weather.gov/ontology#",
      },
    ],
    type: "Feature",
    geometry: {
      type: "Polygon",
      coordinates: [
        [
          [-76.927978699999997, 38.867095599999999],
          [-76.931757199999993, 38.845150499999995],
          [-76.903575899999993, 38.842205499999999],
          [-76.899791599999986, 38.864150299999999],
          [-76.927978699999997, 38.867095599999999],
        ],
      ],
    },
    properties: {
      updated: "2022-04-07T17:34:31+00:00",
      units: "us",
      forecastGenerator: "BaselineForecastGenerator",
      generatedAt: "2022-04-07T19:12:51+00:00",
      updateTime: "2022-04-07T17:34:31+00:00",
      validTimes: "2022-04-07T11:00:00+00:00/P7DT14H",
      elevation: {
        unitCode: "wmoUnit:m",
        value: 75.895200000000003,
      },
      periods: [
        {
          number: 1,
          name: "This Afternoon",
          startTime: "2022-04-07T15:00:00-04:00",
          endTime: "2022-04-07T18:00:00-04:00",
          isDaytime: true,
          temperature: 56,
          temperatureUnit: "F",
          temperatureTrend: null,
          windSpeed: "7 to 12 mph",
          windDirection: "NW",
          icon: "https://api.weather.gov/icons/land/day/tsra,100?size=medium",
          shortForecast: "Showers And Thunderstorms",
          detailedForecast:
            "Showers and thunderstorms. Cloudy, with a high near 56. Northwest wind 7 to 12 mph, with gusts as high as 21 mph. Chance of precipitation is 100%. New rainfall amounts between a tenth and quarter of an inch possible.",
        },
        {
          number: 2,
          name: "Tonight",
          startTime: "2022-04-07T18:00:00-04:00",
          endTime: "2022-04-08T06:00:00-04:00",
          isDaytime: false,
          temperature: 44,
          temperatureUnit: "F",
          temperatureTrend: null,
          windSpeed: "6 to 13 mph",
          windDirection: "W",
          icon: "https://api.weather.gov/icons/land/night/tsra_sct,90/bkn?size=medium",
          shortForecast: "Showers And Thunderstorms then Mostly Cloudy",
          detailedForecast:
            "Showers and thunderstorms before 7pm, then scattered showers and thunderstorms between 7pm and 9pm. Mostly cloudy, with a low around 44. West wind 6 to 13 mph, with gusts as high as 26 mph. Chance of precipitation is 90%. New rainfall amounts between a tenth and quarter of an inch possible.",
        },
        {
          number: 3,
          name: "Friday",
          startTime: "2022-04-08T06:00:00-04:00",
          endTime: "2022-04-08T18:00:00-04:00",
          isDaytime: true,
          temperature: 61,
          temperatureUnit: "F",
          temperatureTrend: null,
          windSpeed: "5 to 13 mph",
          windDirection: "SW",
          icon: "https://api.weather.gov/icons/land/day/rain_showers,20/rain_showers,30?size=medium",
          shortForecast: "Chance Rain Showers",
          detailedForecast:
            "A chance of rain showers after 8am. Mostly sunny, with a high near 61. Southwest wind 5 to 13 mph, with gusts as high as 22 mph. Chance of precipitation is 30%.",
        },
        {
          number: 4,
          name: "Friday Night",
          startTime: "2022-04-08T18:00:00-04:00",
          endTime: "2022-04-09T06:00:00-04:00",
          isDaytime: false,
          temperature: 42,
          temperatureUnit: "F",
          temperatureTrend: null,
          windSpeed: "6 to 12 mph",
          windDirection: "SW",
          icon: "https://api.weather.gov/icons/land/night/rain_showers,40?size=medium",
          shortForecast: "Chance Rain Showers",
          detailedForecast:
            "A chance of rain showers before 2am. Mostly cloudy, with a low around 42. Southwest wind 6 to 12 mph, with gusts as high as 21 mph. Chance of precipitation is 40%. New rainfall amounts less than a tenth of an inch possible.",
        },
        {
          number: 5,
          name: "Saturday",
          startTime: "2022-04-09T06:00:00-04:00",
          endTime: "2022-04-09T18:00:00-04:00",
          isDaytime: true,
          temperature: 56,
          temperatureUnit: "F",
          temperatureTrend: null,
          windSpeed: "7 to 12 mph",
          windDirection: "W",
          icon: "https://api.weather.gov/icons/land/day/bkn/rain_showers,20?size=medium",
          shortForecast: "Partly Sunny then Slight Chance Rain Showers",
          detailedForecast:
            "A slight chance of rain showers after 2pm. Partly sunny, with a high near 56. West wind 7 to 12 mph, with gusts as high as 21 mph. Chance of precipitation is 20%.",
        },
        {
          number: 6,
          name: "Saturday Night",
          startTime: "2022-04-09T18:00:00-04:00",
          endTime: "2022-04-10T06:00:00-04:00",
          isDaytime: false,
          temperature: 39,
          temperatureUnit: "F",
          temperatureTrend: null,
          windSpeed: "8 to 12 mph",
          windDirection: "W",
          icon: "https://api.weather.gov/icons/land/night/rain_showers,20/bkn?size=medium",
          shortForecast: "Slight Chance Rain Showers then Mostly Cloudy",
          detailedForecast:
            "A slight chance of rain showers before 8pm. Mostly cloudy, with a low around 39. Chance of precipitation is 20%.",
        },
        {
          number: 7,
          name: "Sunday",
          startTime: "2022-04-10T06:00:00-04:00",
          endTime: "2022-04-10T18:00:00-04:00",
          isDaytime: true,
          temperature: 52,
          temperatureUnit: "F",
          temperatureTrend: null,
          windSpeed: "9 to 15 mph",
          windDirection: "NW",
          icon: "https://api.weather.gov/icons/land/day/sct?size=medium",
          shortForecast: "Mostly Sunny",
          detailedForecast: "Mostly sunny, with a high near 52.",
        },
        {
          number: 8,
          name: "Sunday Night",
          startTime: "2022-04-10T18:00:00-04:00",
          endTime: "2022-04-11T06:00:00-04:00",
          isDaytime: false,
          temperature: 37,
          temperatureUnit: "F",
          temperatureTrend: null,
          windSpeed: "5 to 14 mph",
          windDirection: "NW",
          icon: "https://api.weather.gov/icons/land/night/few?size=medium",
          shortForecast: "Mostly Clear",
          detailedForecast: "Mostly clear, with a low around 37.",
        },
        {
          number: 9,
          name: "Monday",
          startTime: "2022-04-11T06:00:00-04:00",
          endTime: "2022-04-11T18:00:00-04:00",
          isDaytime: true,
          temperature: 64,
          temperatureUnit: "F",
          temperatureTrend: null,
          windSpeed: "5 to 9 mph",
          windDirection: "W",
          icon: "https://api.weather.gov/icons/land/day/sct?size=medium",
          shortForecast: "Mostly Sunny",
          detailedForecast: "Mostly sunny, with a high near 64.",
        },
        {
          number: 10,
          name: "Monday Night",
          startTime: "2022-04-11T18:00:00-04:00",
          endTime: "2022-04-12T06:00:00-04:00",
          isDaytime: false,
          temperature: 50,
          temperatureUnit: "F",
          temperatureTrend: null,
          windSpeed: "5 to 8 mph",
          windDirection: "S",
          icon: "https://api.weather.gov/icons/land/night/sct?size=medium",
          shortForecast: "Partly Cloudy",
          detailedForecast: "Partly cloudy, with a low around 50.",
        },
        {
          number: 11,
          name: "Tuesday",
          startTime: "2022-04-12T06:00:00-04:00",
          endTime: "2022-04-12T18:00:00-04:00",
          isDaytime: true,
          temperature: 75,
          temperatureUnit: "F",
          temperatureTrend: null,
          windSpeed: "5 to 10 mph",
          windDirection: "SW",
          icon: "https://api.weather.gov/icons/land/day/sct?size=medium",
          shortForecast: "Mostly Sunny",
          detailedForecast: "Mostly sunny, with a high near 75.",
        },
        {
          number: 12,
          name: "Tuesday Night",
          startTime: "2022-04-12T18:00:00-04:00",
          endTime: "2022-04-13T06:00:00-04:00",
          isDaytime: false,
          temperature: 55,
          temperatureUnit: "F",
          temperatureTrend: null,
          windSpeed: "2 to 9 mph",
          windDirection: "SW",
          icon: "https://api.weather.gov/icons/land/night/bkn?size=medium",
          shortForecast: "Mostly Cloudy",
          detailedForecast: "Mostly cloudy, with a low around 55.",
        },
        {
          number: 13,
          name: "Wednesday",
          startTime: "2022-04-13T06:00:00-04:00",
          endTime: "2022-04-13T18:00:00-04:00",
          isDaytime: true,
          temperature: 78,
          temperatureUnit: "F",
          temperatureTrend: null,
          windSpeed: "2 to 10 mph",
          windDirection: "S",
          icon: "https://api.weather.gov/icons/land/day/bkn/rain_showers?size=medium",
          shortForecast: "Partly Sunny then Slight Chance Rain Showers",
          detailedForecast:
            "A slight chance of rain showers after 2pm. Partly sunny, with a high near 78.",
        },
        {
          number: 14,
          name: "Wednesday Night",
          startTime: "2022-04-13T18:00:00-04:00",
          endTime: "2022-04-14T06:00:00-04:00",
          isDaytime: false,
          temperature: 59,
          temperatureUnit: "F",
          temperatureTrend: null,
          windSpeed: "6 to 9 mph",
          windDirection: "S",
          icon: "https://api.weather.gov/icons/land/night/rain_showers?size=medium",
          shortForecast: "Slight Chance Rain Showers",
          detailedForecast:
            "A slight chance of rain showers. Mostly cloudy, with a low around 59.",
        },
      ],
    },
  },
};
